### ISSUE TITLE
ASCII - no shadow

### ISSUE THREAD

**Issue by nikhilindiamail** [helixquar/asciidecorator#2]
Could you please add a version of the default font without shadow? Personally, I like the 'cleaner' look :) Great job on the extension, btw!!
<img width="335" alt="screen shot 2017-07-09 at 3 40 21 pm" src="https://user-images.githubusercontent.com/9480900/27991520-f4789476-64bc-11e7-8cf6-a86eb34f96e1.png">

**Comment by helixquar** [comment]
This extension uses the pre-defined fonts in /patorjk/figlet.js. For a custom font, you would have to do modify the font file and paste it in the fonts directory.

1. Go to the fonts directory. In windows, it is found by default in "%userprofile%\.vscode\extensions\helixquar.asciidecorator-0.0.4\node_modules\figlet\fonts".
2. The default font is "ANSI Shadow.flf". Import this to a figlet font editor (e.g. http://patorjk.com/figlet-editor/) and make the changes that you want.
3. Export the flf file back to the fonts directory.

The downside is that there is no guarantee that your changes are kept after the extension or any of its dependencies are updated.

**Comment by mrv96** [comment]
ANSI Regular is now included in patorjk/figlet.js (https://github.com/patorjk/figlet.js/commit/f96d1453d7adc78458ca8f896b3b3424e61b8481)

I have just installed this extension from VSCode Marketplace but the font is not include.

Could you fix please? Thank you.

**Comment by abettati** [comment]
Any update on this? Fresh install does not include ANSI Regular, I think it would be very useful for mini map visualization too.
Thank you a lot for the awesome extension 😃

**Comment by helixquar** [comment]
@mrv96 @abettati Updated with latest figlet package. "ANSI Regular" should be available now.

**Comment by abettati** [comment]
Yeah it's there, thank you!
