### ISSUE TITLE
[VS Code 1.28.1] "ASCII Decorator: Font Selector" does not work consistently

### ISSUE THREAD

**Issue by roncli** [helixquar/asciidecorator#5]
The option for "ASCII Decorator: Font Selector" no longer seems to be working consistently.  I've only gotten it to work once, and I don't even remember what I did to get it to work, as I've been unable to reproduce it.  The preview still shows up in the Output window, and as a workaround I can copy and paste the text from there to where I need it.

"ASCII Decorator: Default Font" still works fine.

**Comment by MIRAMAXED** [comment]
I have the same problem. Font selector shows me preview, but when I press "Enter", the terminal window just closing.
